/**
 * The KOL portraits — one of one each, given out rather than sold.
 *
 * ## Why this is a list and not a pinned manifest
 *
 * Every other collection here describes itself in a single manifest pinned at
 * creation, because its designs are fixed the moment it exists. This set is
 * not fixed: it grows whenever another SoDEX regular is worth adding, and a
 * manifest would have to be re-pinned and the contract's `baseURI` repointed
 * every time — changing the metadata URL of every token already minted.
 *
 * Kept here instead, adding someone is: pin one image, add one line below,
 * deploy, mint. Nothing already in a wallet is touched.
 *
 * ## Token id is the index
 *
 * Token N carries entry N, so ids stay stable as the list grows. **Once the
 * collection is minted, only ever append.** Reordering or removing an entry
 * would silently repoint a token already in someone's wallet at a different
 * person's portrait.
 *
 * Renumbered 2026-09-26, before anything existed on chain (no KOLs collection
 * in either factory, checked): Keng Noor, Markinho, Stephen, Victor,
 * Farmercist and Takimi were removed, and bΞar, Kagurazaka Fortune, ただのいぬ
 * and ハルのナカミ added. The ids were closed up so the first mint —
 * `mintBatch` numbers tokens sequentially from 1 — lands each portrait on its
 * own id with no gaps.
 */

export interface Kol {
  /** Token id. Also this entry's position — append only, once minted. */
  n: number;
  /** The name they go by. */
  name: string;
  /** Filebase CID of the portrait. */
  image: string;
  /** Their X profile, where they gave one. */
  x?: string;
}

export const KOLS: Kol[] = [
  { n: 1, name: "BTCtensai", image: "QmWp59bT9RZi6qQozSZnfsoT2VC4z2744dZdQTGcGa83tz", x: "https://x.com/BTCtensai" },
  { n: 2, name: "CORTEZ", image: "QmPj319pEoPpg2NqP5ozvk2qxPoMDWjKPm2jMvnENAqi3K", x: "https://x.com/eyupyavuz75" },
  { n: 3, name: "ELIAS", image: "Qmb7cBjWjstatn3QZXj1wfvBv23BtmttEPfJyAmWBBdNG7", x: "https://x.com/eliasing__" },
  { n: 4, name: "LUTZ", image: "QmQ4LmfH4StkAmNLxHfmuz2CKbyJPqvRqiUWzLd2QjxUsC", x: "https://x.com/Lutz_S120" },
  { n: 5, name: "MICK", image: "QmZMufXR1z6QAFE83r9sRiqKBSsDPXhDLb8gFajvpuiHYV", x: "https://x.com/Mickssv" },
  { n: 6, name: "SKIDO", image: "QmRJoNdX43yLpTUMfxt77eCtvNs585Ra5wqcncoyMhnbyP", x: "https://x.com/MR_CRYPTO150" },
  { n: 7, name: "VITALY", image: "QmTNkiWFbiEM1hLDHk6GjC6c7XhUyTGyhg64aQgxqvefkH", x: "https://x.com/vitalythm" },
  { n: 8, name: "0xYeFz", image: "QmYdzZKnNZBvrQ7TKgheAcdXJRp3Yg8t5SYGpQ8v3DW1mM", x: "https://x.com/0xYefz" },
  { n: 9, name: "Vault", image: "QmR3mn5oGzragL4EkMsJE3hp5soTPMX2DLLh61pUxeh6Si", x: "https://x.com/VaultSeek" },
  { n: 10, name: "NFTrader-Crypto", image: "QmeQ23pxiPzEWuW1ZebqEqmBbYdz39KvRBNTrfQZeSwZp7", x: "https://x.com/NftraderCrypto" },
  { n: 11, name: "Ralmix", image: "Qmc5UYEsvfcstnjDdsFYbVmijwEh62P1sgN68pfo2Dd6nC", x: "https://x.com/iRalmix" },
  { n: 12, name: "bΞar", image: "QmQoHrQqt7vz4gD8ZUtB8RDSgw8RC92eg1ytMqHgDpFyod", x: "https://x.com/mato_3535" },
  { n: 13, name: "Kagurazaka Fortune", image: "QmXyTk8yrdp3cViAfxEQTFWpNa8yD5HNaeCgbQs5ov5mts", x: "https://x.com/KagurazakaF" },
  { n: 14, name: "ただのいぬ", image: "QmTwQwMK8VfSjpdPAdpsYi5QpdJep8qr4jED6mNCT7HHza", x: "https://x.com/one_wan_inu" },
  { n: 15, name: "ハルのナカミ", image: "QmS53hQv261bJehBbdT7f14Gnn5MvbGiTXmEzDAJew5B15", x: "https://x.com/yurusanaiinu" },
  { n: 16, name: "tomo&cipher", image: "QmVYfUZCmdrdcAmpDhJPWGLQ5CcQPyvZ3inCZ8KazWwF8g", x: "https://x.com/tomo81782224" },
];

/** "https://x.com/VaultSeek" → "@VaultSeek". */
export const xHandle = (url: string) => `@${url.replace(/\/+$/, "").split("/").pop() ?? ""}`;

/** The collection's slug, matching the metadata route and the contract baseURI. */
export const KOLS_SLUG = "valuemint-kols";

export const KOLS_GATEWAY = "https://ipfs.filebase.io/ipfs";

export const kolImage = (k: Kol) => `${KOLS_GATEWAY}/${k.image}`;

/** The entry a token id carries, or undefined if nothing is minted at that id. */
export function kolForToken(tokenId: number): Kol | undefined {
  return KOLS.find((k) => k.n === tokenId);
}

/**
 * The same portrait, mirrored onto our own origin.
 *
 * `kolImage` above is the canonical one and stays that way: it is what a
 * token's metadata resolves to, and it has to keep pointing at IPFS. This is
 * for /kols, which draws the whole roster at once inside a moving ribbon —
 * twelve gateway round trips in front of the one thing that page exists to
 * show, and a dropped connection leaves a hole in the middle of it.
 *
 * Generated by `metadata/scripts/localise-kols.mjs`, which reads this file. Add
 * an entry above, run it, and the mirror catches up.
 */
export const kolLocal = (k: Kol) => `/kols/roster/${String(k.n).padStart(2, "0")}.webp`;
